language: go

services:
  - docker

go:
  - 1.8

before_script:
  - go get -u github.com/Masterminds/glide
  - glide install

script: 
  - go version
  - go vet $(shell go list github.com/$TRAVIS_REPO_SLUG/... | grep -v vendor)
  - go list -f '{{if len .TestGoFiles}}"gofmt -s -l {{.Dir}}"{{end}}' $(shell go list github.com/$TRAVIS_REPO_SLUG/... | grep -v vendor) | xargs -L 1 sh -c
  - cd $TRAVIS_BUILD_DIR
  - go test -v -race $(go list ./... | grep -v /vendor/)
  - CGO_ENABLED=0 GOOS=$GOOS go build

after_success:
  - sh .travis/deploy_dockerhub.sh